apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-reverse-proxy
  namespace: test-a
  labels:
    app: svc-nginx-reverse-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: nginx-reverse-proxy